version: '3.7'
services:
    bodypix:
        image: bodypix
        init: true
        environment:
            ARCHITECTURE: ResNet50
            IRES: 1
            MULTI: 1
            QBYTES: 4
        build:
            context: ./bodypix
        networks:
            - fakecam
        read_only: true
        ports:
            - ${PORT_BODYPIX}:9000

    fakecam:
        image: fakecam
        init: true
        build:
            context: ./fakecam
        networks:
            - fakecam
        read_only: true
        devices:
            - ${VIDEO_INPUT}:/dev/video0
            - ${VIDEO_OUTPUT}:/dev/video2
        depends_on:
            - bodypix
        command: ["--bodypix-url", "http://bodypix:9000/",
                  "--no-foreground", "--no-background", "--background-blur=50",
                  "--webcam-path", "/dev/video0", "--v4l2loopback-path", "/dev/video2"]

networks:
    fakecam:
